### ISSUE TITLE
`logo` 请勿使用涉及商业版权的图片

### ISSUE THREAD

**Issue by diveDylan** [pregalaxyer/jenkins-deploy#3]

**Comment by diveDylan** [comment]
@luoqiang0831 @Kujo-Jotaro-AAAAA  查看[ icons ](https://fontawesome.com/) 和 [iconfont](https://www.iconfont.cn/)
关键字 `deploy` 找到几个图标，你们看一下选用哪个
![image](https://user-images.githubusercontent.com/28706090/142591597-ee695ca2-da3b-47d9-98bf-1eae209a85a6.png)
![image](https://user-images.githubusercontent.com/28706090/142591668-fba4ce94-ce48-4379-a4ee-dc1c4810fe06.png)

**Comment by Kujo-Jotaro-AAAAA** [comment]
第一个还行
